import { Food } from "./app/shared/models/Food";
import { Tag } from "./app/shared/models/Tag";

export const sample_foods: Food[] = [
  {
    id: '1',
    name: 'Tomatoes',
    cookTime: '5-10',
    price: 50,
    favorite: false,
    origins: ['Italy', 'Mexico'],
    stars: 4.5,
    imageUrl: 'assets/Tomatoes.jpg',
    tags: ['Vegetable', 'Fresh', 'Salad'],
  },
  {
    id: '2',
    name: 'Capsicum',
    price: 160,
    cookTime: '5-10',
    favorite: true,
    origins: ['Central America', 'Mexico'],
    stars: 4.7,
    imageUrl: 'assets/Capsicum.jpg',
    tags: ['Vegetable', 'Fresh', 'Salad'],
  },
  {
    id: '3',
    name: 'Apples',
    price: 200,
    cookTime: '0',
    favorite: true,
    origins: ['Central Asia', 'Europe'],
    stars: 4.8,
    imageUrl: 'assets/Apples.jpg',
    tags: ['Fruit', 'Snack'],
  },
  {
    id: '4',
    name: 'Bananas',
    price: 80,
    cookTime: '0',
    favorite: true,
    origins: ['Southeast Asia', 'India'],
    stars: 4.6,
    imageUrl: 'assets/Bananas.jpeg',
    tags: ['Fruit', 'Snack'],
  },
  {
    id: '5',
    name: 'Carrots',
    price: 70,
    cookTime: '5-10',
    favorite: false,
    origins: ['Iran', 'Afghanistan'],
    stars: 4.2,
    imageUrl: 'assets/Carrots.webp',
    tags: ['Vegetable', 'Root', 'Salad'],
  },
  {
    id: '6',
    name: 'Broccoli',
    price: 250,
    cookTime: '10-15',
    favorite: false,
    origins: ['Italy'],
    stars: 4.3,
    imageUrl: 'assets/Broccoli.webp',
    tags: ['Vegetable', 'Green', 'Salad'],
  },
  {
    id: '7',
    name: 'Strawberries',
    price: 350,
    cookTime: '0',
    favorite: true,
    origins: ['Europe', 'North America'],
    stars: 4.9,
    imageUrl: 'assets/Strawberries.jpeg',
    tags: ['Fruit', 'Berry', 'Snack'],
  },
  {
    id: '8',
    name: 'Oranges',
    price: 120,
    cookTime: '0',
    favorite: false,
    origins: ['China', 'India'],
    stars: 4.5,
    imageUrl: 'assets/Oranges.jpeg',
    tags: ['Fruit', 'Citrus', 'Snack'],
  },
];

export const sample_tags: Tag[] = [
  { name: 'All', count: 8 },
  { name: 'Vegetable', count: 4 },
  { name: 'Fruit', count: 4 },
  { name: 'Fresh', count: 2 },
  { name: 'Salad', count: 3 },
  { name: 'Snack', count: 3 },
  { name: 'Root', count: 1 },
  { name: 'Berry', count: 1 },
  { name: 'Citrus', count: 1 },
];
